### ISSUE TITLE
dc_input_power has multiple values

### ISSUE THREAD

**Issue by skyshelf** [warhammerkid/bluetti_mqtt#19]
This is an amazing piece of work, thank you.

I am using a raspberry pi 400, homeassistant on a Synology nas and a Bluetti AC200max. Everything works well except one problem with the dc_input_power mqtt message. I am using a 15 second interval and there appears to be two mqtt messages. The first one is the correct value, but immediately afterwards the value is resent as in integer ten times the value. I have checked this with MQTT explorer on my PC, so it is not a problem with homeassistant.

I guess I may have set up something incorrectly, as I am far from an expert, but it does seem odd.

**Comment by warhammerkid** [comment]
Nice catch. Looks like I broke it in 0.7.0, but it should be easy for me to fix.
