### ISSUE TITLE
Batterypack Details 

### ISSUE THREAD

**Issue by woody3333** [warhammerkid/bluetti_mqtt#37]
Hi there,

this is not really an issue, just the question about extended function. I'm using AC200MAX extended with two batterypacks. 
Currently there is only the total_battery_percent delivered to Homeassitant.
I just seen via MQTT explorer that the Battery details are already read out and available via MQTT:

pack_details2 = {"percent":58,"voltages":[3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37]}
pack_details3 = {"percent":53,"voltages":[3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38]}
pack_details1 = {"percent":35,"voltages":[3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38]}

I there a possibility to have the charging percentage of each Battery also available within Homeassistant?

Regards and greetings from Germany
Michael

PS: Great work so far and very useful tool for all HA and Bluetti useres.

**Comment by slash5k1** [comment]
Created PR #41 to add support for battery pack details. - just needs to be tested :)

**Comment by woody3333** [comment]
Just tested the new release 0.11.0 and it is working as expected. Well done. Thank you.
