### ISSUE TITLE
Akku Pack Holding Register Addresses?

### ISSUE THREAD

**Issue by tinkercnc** [warhammerkid/bluetti_mqtt#71]
Hi Fellows!
Does someone know the addresses of the separate akku pack properties/values?
I've a AC300 with two B300 and I can't find any meaningful values for
ie:
'cell_voltages' at address 0x0069,  all 16 values are zero.
I scanned the whole range for meaningful values.
Are they on a different "page"?

And on the screen (pic) the packs are on position 2 and 3 despite on which socket they are connected.

![IMG_20230410_175321](https://user-images.githubusercontent.com/5290721/231307883-040f62b6-f16b-4ff9-b015-bb56383d88e1.jpg)

**Comment by warhammerkid** [comment]
The AC300 has a settable value at address 3006 (0x0BBE) that controls what pack data is currently available. Setting that to a number from 1-4 will allow you to page through the pack data for the attached batteries. In my own testing I found that there was some lag between changing the current pack number and the data actually being available, so currently I wait 10 seconds after changing the value before reading the data.

**Comment by tinkercnc** [comment]
Hi Stephen,
thanks for this info. 
Will try this when I am finished with the solar panel installation. :)
I suppose the pack data is then at 0x0069 upward.

BTW: I started this thread.
 https://community.bluettipower.com/t/bluetti-devices-modbus-register-inputs-and-coil-description/8602
and I'm tinkering on this 
https://github.com/tinkercnc/Bluetti_AC300_ESP32.
