### ISSUE TITLE
Device not found on Windows

### ISSUE THREAD

**Issue by atrueresistance** [warhammerkid/bluetti_mqtt#80]
![image](https://github.com/warhammerkid/bluetti_mqtt/assets/7239809/4eff1a62-abae-445f-9b4f-1400c741571b)

Any ideas on why it might not show up? PC is same range as phone to the AC200MAX. Bluetooth is enabled.

**Comment by bxm6306** [comment]
You can only connect one device to your power station at a time using Bluetooth. The scan will only show Bluetti's that are not Bluetooth-connected to another device. If you recently used the Bluetti app on your phone, close it or disable your phone's bluetooth then try the bluetti-mqtt scan again.

**Comment by atrueresistance** [comment]
I did confirm that the AC200MAX Bluetooth state does say disconnected. The desktop is about 12 feet away from the Bluetti main unit, so perhaps it's too far away. I've an Orange Pi 3 LTS coming tomorrow to try in closer proximity. Will update once I receive it.

**Comment by bxm6306** [comment]
On your PC, does your AC200Max show up as a Bluetooth device via the Add device wizard? (do not pair with it)
![image](https://github.com/warhammerkid/bluetti_mqtt/assets/25730493/2d982379-8c4d-4f4e-92ee-ee59b67b0552)

**Comment by atrueresistance** [comment]
Nope, just one Unknown device. I'll try a laptop closer to the unit.
![image](https://github.com/warhammerkid/bluetti_mqtt/assets/7239809/7a46c52d-981b-4056-aaf3-9c3b4fbb11ec)

**Comment by bxm6306** [comment]
Yeah, worth a try. Indoor range is heavily impacted by obstructions and other 2.4GHz signal interference as well as the sensitivity of your client's bluetooth transceiver.

**Comment by atrueresistance** [comment]
From the laptop same distance as the desktop it shows up. Thank you for the help.
![image](https://github.com/warhammerkid/bluetti_mqtt/assets/7239809/b9666a8c-5f7f-494d-a0ab-c10a796197d4)
