### ISSUE TITLE
Support for multiple Bluetti devices

### ISSUE THREAD

**Issue by dabene1408** [warhammerkid/bluetti_mqtt#9]
Hi, 
Is there a way to collect Data of 2 or more battery packs with the script?

**Comment by warhammerkid** [comment]
Do you mean multiple power stations or multiple batteries connected to a single power station. Currently you can monitor multiple power stations simultaneously by simply providing additional bluetooth addresses to the script as arguments.

**Comment by dabene1408** [comment]
Yes, i meant multiple power stations. Thanks for the reply

**Comment by dabene1408** [comment]
I tried it with the newest version of your script and it worked. The only misbehavior i noticed is that the measurements getting very irregularly despite of the --interval parameter
