### ISSUE TITLE
Simple Command Example Request

### ISSUE THREAD

**Issue by danricho** [warhammerkid/bluetti_mqtt#94]
Hi,

I have been using this library with my AC70 and I'm able to successfully monitor it's state. 
I am using [bxm6306's fork which adds AC70](https://github.com/bxm6306/bluetti_mqtt/tree/patch-2). The following script is what I am using to view it's state... it is based upon the gist [warhammerkid simple_polling_example.py](https://gist.github.com/warhammerkid/bb00ec3bba098587e7157724b79de22a), but did require some updates as the bluetti library has changed.

What I'm hopping for is a similar example which allows commands like DC OUTPUT ON/OFF and AC OUTPUT ON/OFF, as I'm not using the MQTT side of the library. Unfortunately I'm not finding it easy to navigate the library code to figure it out (I'm not a GREAT coder).

Thanks for all the great work that has gone into this library!

```python

from bluetti_mqtt.bluetooth import (check_addresses, BluetoothClient, ParseError, BadConnectionError)

data = {}

async def monitor_device(address):

  devices = await check_addresses({address})
  if len(devices) == 0:
    print(f"BLUETTI        | COULDN'T FIND A BLUETTI")

  else:
    device = devices[0]
    client = BluetoothClient(device.address)
    asyncio.get_running_loop().create_task(client.run())

    counter = 0
    while not client.client.is_connected and counter < 10:
      print(f"BLUETTI        | WAITING TO CONNECT")
      counter += 1
      await asyncio.sleep(0.5)
      continue

    for command in device.polling_commands:      
      response_future = await client.perform(command)
      try:
        response = await response_future
        body = command.parse_response(response)
        parsed = device.parse(command.starting_address, body) 
        data.update(parsed)

    print(data)

async def main():
  while True:
    await monitor_device(ADDRESS)
    await asyncio.sleep(5)

asyncio.run(main())

```

**Comment by bobthebuilder4711** [comment]
If you're not a "GREAT" coder then why not simply install an MQTT broker and use this program that way?

And for monitoring you can then even use something like MQTT Explorer.

**Comment by danricho** [comment]
Hi @bobthebuilder4711,

The main reason is that I’m trying to integrate it into a larger system I’ve built up and to add MQTT just to service one component seemed silly to me.

I have however figured everything out that I asked here and will share it here when I get a chance to clean it up into a neat script that will let anyone else use it similarly.

I’ll close this for now. Cheers!
