### ISSUE TITLE
Support of Bluetti Balcony System

### ISSUE THREAD

**Issue by DerMuffin** [warhammerkid/bluetti_mqtt#96]
Anyone already have a look in integrate the D100S and A80 unit into this project?

I try to add them just by paste their MAC-Adresses into the config but it seemed like that will crash the whole script.

Thanks guys!

**Comment by DerMuffin** [comment]
Any news on this? I have this system but dont know how to reverse engineer the data to work with it

**Comment by JohnFLoki** [comment]
Look here: https://pypi.org/project/bluetti-mqtt/ 
On the bottom are instructions how to get the data.
